@startuml
|Administrator|
start
:Open Application PPMS;
|System|
:Show PPMS Window>
|Administrator|
:Click General Tab;
:Choose Project;
:Click on Search Inputbox;
:Fill "Template";
:Click Filter;
|System|
:Show List ofTemplate>
stop
@enduml