@startuml
|Robot|
start
:Find Path From Computer (In Config File);
if(Have a path?) then(Have) 
|System|
:Show Path>
|Robot|
if(Have Type Excel(.xlms)?) then(Have)
if(Have SO Number?) then(Have)
|System|
:Get SO Number;
stop
|Robot|
else(Not Have) 
endif
else(Not Have) 
endif
else(Not Have) 
endif
|Robot|
end
@enduml