@startuml
|Robot|
start
:หาไฟล์ Excel ในคอมพิวเตอร์;
|System|
:แสดงไฟล์ที่เก็บไฟล์ Excel ในคอมพิวเตอร์>
|Robot|
if (มีเลข SO ในชื่อไฟล์ไหม?) then (มี)
    : เก็บค่าเลข SO จากชื่อไฟล์;
|System|
    : รับค่าเลข SO;
else (ไม่มี)
|Robot|    
    end
|System|
endif
stop
@enduml