@startuml
|Robot|
start
:เปิดไฟล์ Excel;
|System|
:แสดงหน้าต่าง Excel>
|Robot|
:อ่านข้อมูลใน Excel;
if (เช็คข้อมูลว่าตรงตาม Pattern ไหม?) then (ตรง)
    : เก็บข้อมูลใน Excel;
    : ส่งข้อมูลเข้าระบบ;
|System|
    : รับค่าข้อมูล;
else (ไม่ตรง)
|Robot|    
    end
|System|
endif
stop
@enduml