@startuml
|Robot|
start
:Open Excel File;
|System|
:Show Excel Window>
|Robot|
:Read Excel File;
if (Checking Format) then (Correct)
    : Get Data From Excel;
    : Remember Value;
|System|
    : Handle Value;
else (Incorrect)
|Robot|    
end
endif
|System|
stop
@enduml