@startuml
|Robot|
start
:Open Application PPMS;
|System|
:Show PPMS Window>
|Robot|
:Click on Search Inputbox;
:Put SO Number in Inputbox<
:Click Filter;
if(Find SO Number?) then (Found)
|System|
:Show Project on Search>
else(Not Found)
|Robot|
end
|System|
endif
stop
@enduml