@startuml
|Robot|
|System|
start
|Robot|
|System|
:Show Worksheet Window>
|Robot|
:Choose Task;
:Click Icon New Task assignment;
|System|
:Show text input below that task>
|Robot|
:Fill resource <
:Press Enter; 
:Click Icon Save;
stop
@enduml