@startuml
|Robot|
start
:Send Status Exception;
|System|
:Handle Status Exception;
|Robot|
if(Status Check) then (Success)
:แจ้งเตือนไปยัง Email ว่า "RPA Error{ErrorException}";
else(Failed)
:แจ้งเตือนไปยัง Email ว่า "RPA Success";
endif
stop
@enduml