@startuml
|Service Admin|
start
:เปิด Browser Aplication;
:ใส่ Url;
|System|
:แสดงหน้า Web Broswer>
|Service Admin|
:คลิกที่ E-applications;
|System|
:แสดงหน้า E-application>
|Service Admin|
:เลือก PPMS;
|System|
:แสดงหน้า Login>
|Service Admin|
repeat
:กรอก Username & Password;
:คลิก Login;
repeat while (เช็ค ข้อมูล) is (ไม่ถูกต้อง)
->ถูกต้อง;
|System|
:แสดงหน้า Aplication PPMS>
stop
@enduml