@startuml
|Administrator|
start
:Open Browser Aplication;
:Put Url;
|System|
:Show Web Broswer>
|Administrator|
:Click E-applications;
|System|
:Show E-application>
|Administrator|
:Choose PPMS;
|System|
:Show Login>
|Administrator|
repeat
:Fill Username & Password;
:Click Login;
repeat while (Data Checking) is (Incorrect)
->Correct;
|System|
:Show Aplication PPMS>
stop
@enduml