@startuml
|Service Admin|
|System|
start
:แสดงหน้า PPMS>
|Service Admin|
:คลิกที่แถบเมนู Service;
:เลือก Contracts;
|System|
:ปรากฎข้อมูลลูกค้า ที่มาจาก SAP>
|Service Admin|
:ใส่เลข SO. ที่ช่อง Search <
:คลิก Filter;
|System|
:ปรากฎบริษัทลูกค้า>
|Service Admin|
:คลิกที่ไฟล์ SAP Client GT;
:คลิกที่บริษัท;
:คลิกที่ปุ่ม Action ทางด้านขวา;
:เลือก Create Contracts;
:ใส่ข้อมูล Contract ที่นำมาจาก POS <
:กด Save;
stop
@enduml