@startuml
|Administrator|
|System|
start
:Show PPMS Window>
|Administrator|
:Click Service in menu bar;
:Choose Contracts;
|System|
:Show Data Customer from SAP>
|Administrator|
:Fill SO Number on Search Inputbox <
:Click Filter;
|System|
:Show Customer Company>
|Administrator|
:Click on SAP Client GT File;
:Click on Company;
:Click on Action Button on the right;
:Choose Create Contracts;
:Fill Data Contract From POS <
:Click Save;
stop
@enduml