@startuml
|Administrator|
|System|
start
:Show PPMS Window>
|Administrator|
:Click Service on menu bar;
:เลือก Contracts;
|System|
:Show Customer Data From SAP>
|Administrator|
:Fill SO Number on Search inputbox <
:Click Filter;
|System|
:Show Customer Company>
|Administrator|
:Click on SAP Client GT;
:Click on Company;
:Right Click on Contract for Create;
:Choose Create Project;
:Fill Data Contract From PM or Service Lead sent into (From Email) <
:Click Save;
stop
@enduml