@startuml
|Robot|
|System|
start
|Robot|
|System|
:แสดงหน้าต่าง worksheet>
|Robot|
:คลิกเลือก Task;
:คลิกที่ Icon New Task assignment;
|System|
:ปรากฎ text input ใน Task ที่เลือก>
|Robot|
if(เลือกการ add) then (กรอก)
:กรอกชื่อที่ได้มาจาก resource <
:กด Enter;
else
:เลือกจาก dropdown;
|System|
:ปรากฎชื่อให้เลือก>
:คลิกเลือกชื่อ; 
endif
|Robot|
:คลิก Icon Save;
stop
@enduml