@startuml
|Robot|
start
:ส่งข้อมูล Status Exception;
|System|
:ดึงข้อมูล Status Exception;
|Robot|
if(Status Check) then (Success)
:แจ้งเตือนไปยัง Email ว่า "RPA Error";
else(Failed)
:แจ้งเตือนไปยัง Email ว่า "RPA Success";
endif
stop
@enduml